[
    {
      "brand": "Adidas",
      "product Name":"Cartoon Astronaut T-Shirts",
      "ratings":5,
      "price":$92,
      "gender":"Female",
      "img":"image",
      "sizes":["S","M","XL","XXL"],
    },
    {
      "brand": "Adidas",
      "product Name":"Shirts",
      "ratings":5,
      "price":$92,
      "gender":"Female",
      "img":"image",
      "sizes":["S","M","XL","XXL"],
    },
    {
        "brand": "Mayil",
        "product Name":"Kurtis",
        "ratings":5,
        "price":$22,
        "gender":"Female",
        "img":"image",
        "sizes":["S","M","XL","XXL"],
    },
    {   "brand": "pratibha",
        "product Name":"Sarees",
        "ratings":5,
        "price":$32,
        "gender":"Female",
        "img":"image",
    },
    {
        "brand": "Leriya",
        "product Name":"Western",
        "ratings":5,
        "price":$92,
        "gender":"Female",
        "img":"image",
        "sizes":["S","M","XL","XXL"],
    },
    {
     "brand": "Smart",
        "product Name":"Kids T-shirt",
        "ratings":5,
        "price":$72,
        "gender":"male",
        "img":"image",
        "sizes":["S","M","XL","XXL"],
    },
    {  "brand": "lush",
        "product Name":"wedding lehengas",
        "ratings":5,
        "price":$58,
        "gender":"Female",
        "img":"image",
        "sizes":["S","M","XL","XXL"],
    },
    {
        "brand": "Modern",
        "product Name":"Kids shirt",
        "ratings":5,
        "price":$42,
        "gender":"male",
        "img":"image",
        "sizes":["S","M","XL","XXL"],
    },
]